title: Timofey Khomutnikov
description: >
  **I am Timofey Khomutnikov**, iOS software engineer @ Avito
copyright: "2017"
sass:
  sass_dir: assets/sass
url: http://localhost:4000
disqus_shortname: Khomutnikov
facebook_username: "tima.khomutnikov"
twitter_username: "KhomTima"
linkedin_username: "timofeyk"
instagram_username: "timakhom/"
github_username:  "khomTima"
email: "tima.khom@gmail.com"
gems: [jekyll-paginate]
paginate_path: "/page/:num/"
paginate: 5
